spring:
  application:
    name: algafood-api
  threads:
    virtual:
      enabled: true
  datasource:
    username: root
    password: password333
    url: jdbc:mysql://localhost:3306/algafood?createDatabaseIfNotExist=true&serverTimezone=UTC
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: true
  flyway:
    locations: classpath:db/migration,classpath:db/testdata
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: ${API_EMAIL_KEY}
  freemarker:
    settings:
      locale: pt_BR
server:
  error:
    include-stacktrace: on_param
algafood:
  email:
    remetente: thomazllrdev@gmail.com
    impl: smtp
    sandbox-destinatario: teste@algafood.com.br
  storage:
    local:
      diretorio-fotos: /home/thomazllr/Desktop/catalago
    s3:
      id-chave-acesso: ${ID_CHAVE_ACESSO}
      chave-acesso-secreta: ${CHAVE_ACESSO_SECRETA}
      bucket: algafood-test-thomaz
      regiao: us-east-1
      diretorio-fotos: catalogo
    tipo: s3