spring:
  application:
    name: algafood-api
  threads:
    virtual:
      enabled: true
  datasource:
    username: root
    password: password333
    url: jdbc:mysql://localhost:3306/algafood?serverTimezone=UTC
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: true
server:
  tomcat:
    threads:
      max: 20
  error:
    include-stacktrace: on_param
